PPW/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
    path('story1/', include('story1.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('activity/', include('activity.urls')),
    path('story7/', include('story7.urls')),
    path('books/', include('books.urls')),
    path('accounts/', include('story9.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls'))
]

jadwal/urls.py
from django.urls import path, include
from . import views

app_name = 'jadwal'
urlpatterns = [
    path('', views.add_matkul, name="add_matkul"),
    path('view_matkul', views.view_matkul, name="view_matkul"),
    path('delete/<id>', views.delete_jadwal, name="delete_matkul"),
    path('detail/<id>', views.detail, name="detail"),
]

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    Subject = models.CharField(max_length=50)
    Lecturer = models.CharField(max_length=50)
    Credits = models.CharField(max_length=50)
    Description = models.TextField(max_length=100)
    Semester = models.CharField(max_length=50)
    Room = models.CharField(max_length=50, default="Online Class")

jadwal/forms.py
from django import forms

from .models import Jadwal

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = ['Subject', 'Lecturer', 'Credits', 'Description', 'Semester', 'Room']

        widgets = {
            'Subject':forms.TextInput(attrs={'class': 'form-control'}),
            'Lecturer':forms.TextInput(attrs={'class': 'form-control'}),
            'Credits':forms.TextInput(attrs={'class': 'form-control'}),
            'Description':forms.TextInput(attrs={'class': 'form-control'}),
            'Semester':forms.TextInput(attrs={'class': 'form-control'}),
            'Room':forms.TextInput(attrs={'class': 'form-control'}),
        }

jadwal/views.py
from django.shortcuts import render, redirect
from .models import Jadwal
from .forms import MatkulForm

# Create your views here.
def add_matkul(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            jadwal = form.save()
            jadwal.save()
            return redirect('jadwal:view_matkul')
    else:
        form = MatkulForm()
    
    return render(request, 'add_matkul.html', {'form': form})

def delete_jadwal(request, id):
    Jadwal.objects.get(id=id).delete()
    return redirect('jadwal:view_matkul')

def view_matkul(request):
    semua_jadwal = Jadwal.objects.order_by('Subject')
    return render(request, 'view_matkul.html', {'semua_jadwal': semua_jadwal})

def detail(request, id):
    detail = Jadwal.objects.get(id=id)
    return render(request, 'detail.html', {'detail_matkul': detail})

jadwal/templates/add_matkul.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nadya Shelim</title>
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

    {% block content %}
<body>
    <div id="grad1">
      <div class="add-matkul">
        <p>ADD SCHEDULE</p><br>
        <form method="POST">
          {% csrf_token %}
          <div class="mr-auto ml-auto" style="width:50%;">
              {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
              {% endfor %}
            <br>
            <div class="container">
              <button type="submit" class="btn" style="background-color: white; color: black;">Submit</button>
            </div>
          </div>
        </form>
        
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
    {% endblock content %}

</html>

jadwal/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nadya Shelim</title>
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

    {% block content %}
<body>

    <div class="detail-matkul">
        <p>DETAIL</p><br>
        <p style="font-size: 20px;">Subject : {{ detail_matkul.Subject }}</p><br>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Lecturer</th>
                <td>{{ detail_matkul.Lecturer }}</td>
            </tr>
            <tr>
                <th scope="col">Number of Credits</th>
                <td>{{ detail_matkul.Credits }}</td>
            </tr>
            <tr>
                <th scope="col">Description</th>
                <td>{{ detail_matkul.Description }}</td>
            </tr>
            <tr>
                <th scope="col">Semester</th>
                <td>{{ detail_matkul.Semester }}</td>
            </tr>
            <tr>
                <th scope="col">Room</th>
                <td>{{ detail_matkul.Room }}</td>
            </tr>

            </thead>
            <tbody>

        </table>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
    {% endblock content %}

</html>

jadwal/templates/view_matkul.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nadya Shelim</title>
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

    {% block content %}
<body>

    <div class="show-matkul">
        <p>SCHEDULE</p><br>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Subject</th>
                <th scope="col">Lecturer</th>
                <th scope="col">Number of Credits</th>
                <th scope="col">Description</th>
                <th scope="col">Semester</th>
                <th scope="col">Room</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>

            {% for jadwal in semua_jadwal %}
            <tr>
                <td>
                    <a href="{% url 'jadwal:detail' id=jadwal.id %}">{{ jadwal.Subject }}</a>
                </td>
                <td>{{ jadwal.Lecturer }}</td>
                <td style="text-align: center;">{{ jadwal.Credits }}</td>
                <td>{{ jadwal.Description }}</td>
                <td>{{ jadwal.Semester }}</td>
                <td>{{ jadwal.Room }}</td>
                <td>
                    <a class="btn" style="background-color: salmon; color: white;" href="{% url 'jadwal:delete_matkul' id=jadwal.id %}" role="button">Delete Subject</a>
                </td>
            </tr>
            
            {% endfor %}
            </tbody>
        </table>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
    {% endblock content %}

</html>