PPW/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
    path('story1/', include('story1.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('activity/', include('activity.urls')),
    path('story7/', include('story7.urls')),
    path('books/', include('books.urls')),
    path('accounts/', include('story9.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls'))
]

activity/urls.py
from django.urls import path, include
from . import views

app_name = 'activity'
urlpatterns = [
    path('', views.add_url_test, name="add_activity"),
    path('viewactivity', views.add_participant, name="view_activity"),
]

books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.buku, name="buku"),
    path('data/', views.data, name="data"),
]

jadwal/urls.py
from django.urls import path, include
from . import views

app_name = 'jadwal'
urlpatterns = [
    path('', views.add_matkul, name="add_matkul"),
    path('view_matkul', views.view_matkul, name="view_matkul"),
    path('delete/<id>', views.delete_jadwal, name="delete_matkul"),
    path('detail/<id>', views.detail, name="detail"),
]

story1/urls.py
from django.urls import path, include
from . import views

app_name = 'story1'
urlpatterns = [
    path('', views.home, name="home"),
]

story3/urls.py
from django.urls import path, include
from . import views

app_name = 'story3'
urlpatterns = [
    path('', views.index, name="index"),
    path('about', views.about, name="about"),
    path('experience', views.experience, name="experience"),
]

story7/urls.py
from django.urls import path, include
from . import views

app_name = 'story7'
urlpatterns = [
    path('', views.accordion, name="accordion"),
]

story9/urls.py
from django.urls import path
from story9.views import SignUpView
from . import views

app_name = 'story9'

urlpatterns = [
    path('masuk', views.masuk, name='masuk'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', SignUpView.as_view(), name='signup'),
]

books/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    Subject = models.CharField(max_length=50)
    Lecturer = models.CharField(max_length=50)
    Credits = models.CharField(max_length=50)
    Description = models.TextField(max_length=100)
    Semester = models.CharField(max_length=50)
    Room = models.CharField(max_length=50, default="Online Class")

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms

from .models import Jadwal

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = ['Subject', 'Lecturer', 'Credits', 'Description', 'Semester', 'Room']

        widgets = {
            'Subject':forms.TextInput(attrs={'class': 'form-control'}),
            'Lecturer':forms.TextInput(attrs={'class': 'form-control'}),
            'Credits':forms.TextInput(attrs={'class': 'form-control'}),
            'Description':forms.TextInput(attrs={'class': 'form-control'}),
            'Semester':forms.TextInput(attrs={'class': 'form-control'}),
            'Room':forms.TextInput(attrs={'class': 'form-control'}),
        }

books/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import requests
import json

# Create your views here.
def buku(request):
    return render(request, 'books.html')

def data(request):
    arg = request.GET['q']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    req = requests.get(url)
    data = json.loads(req.content)
    return JsonResponse(data, safe=False)

jadwal/views.py
from django.shortcuts import render, redirect
from .models import Jadwal
from .forms import MatkulForm

# Create your views here.
def add_matkul(request):
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            jadwal = form.save()
            jadwal.save()
            return redirect('jadwal:view_matkul')
    else:
        form = MatkulForm()
    
    return render(request, 'add_matkul.html', {'form': form})

def delete_jadwal(request, id):
    Jadwal.objects.get(id=id).delete()
    return redirect('jadwal:view_matkul')

def view_matkul(request):
    semua_jadwal = Jadwal.objects.order_by('Subject')
    return render(request, 'view_matkul.html', {'semua_jadwal': semua_jadwal})

def detail(request, id):
    detail = Jadwal.objects.get(id=id)
    return render(request, 'detail.html', {'detail_matkul': detail})

story1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

story3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def experience(request):
    return render(request, 'experience.html')

story7/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render (request, 'accordion.html')

story9/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

def masuk(request):
    return render(request, "story3/templates/index.html")

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/story3/templates/index.html')
    else:
        form = AuthenticationForm()
    return render(request, "registration/login.html", {'form': form})

def logout(request):
    logout(request)
    return redirect('/')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  {% block head %}
  {% endblock %}
  {% block meta %}
  {% endblock meta %}
  
</head>

{% block navbar %}
<body>
</body>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand logo custom-margin" href="#">NADY'S</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto custom-margin">
          <li class="nav-item active">
            <a class="nav-link nav-links" href="{% url 'story3:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-links" href="{% url 'story3:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-links" href="{% url 'story3:experience' %}">Experiences</a>
          </li>
          <li class="nav-item">
              <a class="nav-link nav-links" href="{% url 'story1:home' %}">Story 1</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-links" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Schedule
            </a>
            <div class="dropdown-menu dropdown-style" aria-labelledby="dropdownMenuLink" style="background-color:#a4b9f0f9;">
              <a class="dropdown-item" href="{% url 'jadwal:add_matkul' %}" style="color: white;">Add</a>
              <a class="dropdown-item" href="{% url 'jadwal:view_matkul' %}" style="color: white;">View</a>
            </div>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle nav-links" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Activity
              </a>
              <div class="dropdown-menu dropdown-style" aria-labelledby="dropdownMenuLink" style="background-color:#a4b9f0f9;">
                <a class="dropdown-item" href="{% url 'activity:add_activity' %}" style="color: white;">Add</a>
                <a class="dropdown-item" href="{% url 'activity:view_activity' %}" style="color: white;">View</a>
                <a class="dropdown-item" href="{% url 'story7:accordion' %}" style="color: white;">Story 7</a>
                <a class="dropdown-item" href="{% url 'books:buku' %}" style="color: white;">Pick a Book</a>
              </div>
            </li>
        </ul>
          
        {% if user.is_authenticated %}
        <a class="nav-link" style="color: white;" href="{% url 'logout' %}">Log Out</a>
        {% else %}
        <a class="nav-link" style="color: white;" href="{% url 'story9:signup' %}">Sign Up</a>
        <a class="nav-link" style="color: white;" href="{% url 'login' %}">Log In</a>
        {% endif %}


    </div>
  </nav>
{% endblock navbar %}

  {% block content %}
  {% endblock content %}
</html>